### ISSUE TITLE
the repo is very heavy

### ISSUE THREAD

**Issue by CarloLucibello** [zuoxingdong/lagom#193]
Hi, 
thanks for your nice work. For some reason, the whole repo takes a few GBs (which is a little bit weird):
```
[carlo@x1 Git]$ git clone https://github.com/zuoxingdong/lagom
Clone in 'lagom' in corso...
remote: Enumerating objects: 456, done.
remote: Counting objects: 100% (456/456), done.
remote: Compressing objects: 100% (447/447), done.
Receiving objects:  16% (5160/31273), 537.01 MiB | 3.35 MiB/s
 ```

**Comment by zuoxingdong** [comment]
Hi @CarloLucibello , thank you for your interest in the repo.

Indeed, the current repo is quite heavily sized, the reason is for each RL baseline, we had provided the checkpoint files (for each environment and each random seed also, that's why it scales up). This is for easier reproducibility of the figures and for users who wanna quickly generate animations of checkpoint files. 

Indeed, this is very inconvenient, I am still thinking about what can be a good solution.

Something like to separate lagom and lagom-baselines as two different repos. 

Any comment about this ? :)

**Comment by CarloLucibello** [comment]
I would keep the baselines in the repo and provide the checkpoints through links to some hosting service and also have a python interface to handle the download for convenience. 
As an intermediate solution, maybe you could delete the checkpoints from master, so that people can comfortably clone the repo, and let the full code + checkpoints live on a separate branch, to be also always kept in sync with master?

**Comment by zuoxingdong** [comment]
Thanks for the suggestion @CarloLucibello , I am currently working on the solution, as I prefer to directly provide a zipped logs managed by Git-LFS and python script to handle the zipping and unzipping process automatically.

However, it turns out that the main reason why the repo is so heavy to clone is due to history, there were many .jpg and checkpoints files in the past commits, they always stay in the historical trackings.

After trying `git gc --auto`, it seems the repo remains large. So I am trying to find a way to clean up those files in `./git` :)

**Comment by zuoxingdong** [comment]
Hi @CarloLucibello , I've updated the repo just now. The solution is that all the loggings are compressed and hosted in Dropbox, and Python script also provided to automatically recover them. The details are documented under the folder `baselines`

Now it should be light enough for cloning, could you help to try again ? Thanks

**Comment by CarloLucibello** [comment]
thanks, much better
